/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDependencyCreateRequest } from '../../models/task-dependency-create-request';
import { TaskDependencyResponse } from '../../models/task-dependency-response';

export interface CreateDependency$Params {

/**
 * Dynamic task ID that gains the dependency
 */
  id: number;
      body: TaskDependencyCreateRequest
}

export function createDependency(http: HttpClient, rootUrl: string, params: CreateDependency$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDependencyResponse>> {
  const rb = new RequestBuilder(rootUrl, createDependency.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDependencyResponse>;
    })
  );
}

createDependency.PATH = '/v1/tasks/{id}/dependencies';
