/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DynamicTaskCreateRequest } from '../../models/dynamic-task-create-request';
import { DynamicTaskResponse } from '../../models/dynamic-task-response';
import { StaticTaskCreateRequest } from '../../models/static-task-create-request';
import { StaticTaskResponse } from '../../models/static-task-response';

export interface CreateTask$Params {
      body: (DynamicTaskCreateRequest | StaticTaskCreateRequest)
}

export function createTask(http: HttpClient, rootUrl: string, params: CreateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<(DynamicTaskResponse | StaticTaskResponse)>> {
  const rb = new RequestBuilder(rootUrl, createTask.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(DynamicTaskResponse | StaticTaskResponse)>;
    })
  );
}

createTask.PATH = '/v1/tasks';
