/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DynamicTaskResponse } from '../../models/dynamic-task-response';
import { StaticTaskResponse } from '../../models/static-task-response';

export interface GetTask$Params {

/**
 * Task ID
 */
  id: number;
}

export function getTask(http: HttpClient, rootUrl: string, params: GetTask$Params, context?: HttpContext): Observable<StrictHttpResponse<(DynamicTaskResponse | StaticTaskResponse)>> {
  const rb = new RequestBuilder(rootUrl, getTask.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(DynamicTaskResponse | StaticTaskResponse)>;
    })
  );
}

getTask.PATH = '/v1/tasks/{id}';
