/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DynamicTaskResponse } from '../../models/dynamic-task-response';
import { DynamicTaskUpdateRequest } from '../../models/dynamic-task-update-request';
import { StaticTaskResponse } from '../../models/static-task-response';
import { StaticTaskUpdateRequest } from '../../models/static-task-update-request';

export interface UpdateTask$Params {

/**
 * Task ID
 */
  id: number;
      body: (DynamicTaskUpdateRequest | StaticTaskUpdateRequest)
}

export function updateTask(http: HttpClient, rootUrl: string, params: UpdateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<(DynamicTaskResponse | StaticTaskResponse)>> {
  const rb = new RequestBuilder(rootUrl, updateTask.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(DynamicTaskResponse | StaticTaskResponse)>;
    })
  );
}

updateTask.PATH = '/v1/tasks/{id}';
