/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrganizationInvitationsResponse } from '../../models/organization-invitations-response';

export interface GetInvitations$Params {

/**
 * Organization ID
 */
  organizationId: string;
}

export function getInvitations(http: HttpClient, rootUrl: string, params: GetInvitations$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganizationInvitationsResponse>> {
  const rb = new RequestBuilder(rootUrl, getInvitations.PATH, 'get');
  if (params) {
    rb.path('organizationId', params.organizationId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrganizationInvitationsResponse>;
    })
  );
}

getInvitations.PATH = '/v1/organizations/{organizationId}/invitations';
