/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlanRequest } from '../../models/plan-request';
import { WorkSlotResponse } from '../../models/work-slot-response';

export interface Plan$Params {
      body: PlanRequest
}

export function plan(http: HttpClient, rootUrl: string, params: Plan$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkSlotResponse>>> {
  const rb = new RequestBuilder(rootUrl, plan.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkSlotResponse>>;
    })
  );
}

plan.PATH = '/v1/plan';
