import { TranslocoTestingModule } from '@jsverse/transloco';

// Inline the translations needed for tests to pass
// This avoids fs/path issues with Angular's compiler
const en: Record<string, string> = {
  NAV_LIST_VIEW: 'List View',
  NAV_CALENDAR_VIEW: 'Calendar View',
  NAV_NEW_TASK: 'New Task',
  NAV_PLAN_TASKS: 'Plan Tasks',
  NAV_SETTINGS: 'Settings',
  NAV_LOGOUT: 'Logout',
  TOPBAR_SEARCH_PLACEHOLDER: 'Search',
  TOPBAR_CLEAR_SEARCH: 'Clear search',
  TOPBAR_FILTER_ORGANIZATION: 'Organization',
  TOPBAR_ALL_ORGANIZATIONS: 'All organizations',
  TOPBAR_RESULTS: 'Results',
  TOPBAR_NO_MATCHES: 'No matches found',
  SETTINGS_TITLE: 'Settings',
  SETTINGS_CLOSE: 'Close settings',
  SETTINGS_NAV_ACCOUNT: 'Account & Security',
  SETTINGS_NAV_APPEARANCE: 'Appearance',
  SETTINGS_NAV_ORGANIZATIONS: 'Organizations & Profiles',
  SETTINGS_NAV_WORK_PREFERENCES: 'Work Preferences',
  SETTINGS_APPEARANCE_TITLE: 'Appearance',
  SETTINGS_APPEARANCE_DESC: 'Customize how ChronoScope looks for you.',
  SETTINGS_APPEARANCE_THEME_TITLE: 'Color Theme',
  SETTINGS_APPEARANCE_THEME_DESC: 'Choose your preferred color scheme.',
  SETTINGS_APPEARANCE_THEME_LIGHT: 'Light',
  SETTINGS_APPEARANCE_THEME_DARK: 'Dark',
  SETTINGS_APPEARANCE_THEME_SYSTEM: 'System',
  SETTINGS_APPEARANCE_LANGUAGE_TITLE: 'Language',
  SETTINGS_APPEARANCE_LANGUAGE_DESC: 'Choose your preferred display language.',
  SETTINGS_ACCOUNT_TITLE: 'Account & Security',
  SETTINGS_ACCOUNT_DESC: 'Manage your account details and security settings.',
  SETTINGS_ACCOUNT_MANAGE: 'Manage Account',
  SETTINGS_ACCOUNT_LINKED_TITLE: 'Linked Accounts',
  SETTINGS_ACCOUNT_LINKED_DESC: 'Accounts you have linked together.',
  SETTINGS_ACCOUNT_MERGE_TITLE: 'Merge Accounts',
  SETTINGS_ACCOUNT_MERGE_DESC: 'Link another account by entering its email address. Both accounts will be merged.',
  SETTINGS_ACCOUNT_MERGE_PLACEHOLDER: 'account@example.com',
  SETTINGS_ACCOUNT_MERGE_BUTTON: 'Send Merge Request',
  SETTINGS_ORGANIZATIONS_TITLE: 'Organizations & Profiles',
  SETTINGS_ORGANIZATIONS_DESC: 'Manage your organization memberships and linked accounts.',
  SETTINGS_ORGANIZATIONS_YOUR_TITLE: 'Your Organizations',
  SETTINGS_ORGANIZATIONS_YOUR_DESC: 'Organizations you are currently a member of.',
  SETTINGS_ORGANIZATIONS_MANAGE_TITLE: 'Manage Organizations',
  SETTINGS_ORGANIZATIONS_MANAGE_DESC: 'Invite People to Organizations.',
  SETTINGS_ORGANIZATIONS_ADMIN: 'Admin',
  SETTINGS_ORGANIZATIONS_MANAGE_CONTENT: 'Manage {{name}} here',
  SETTINGS_ORGANIZATIONS_INVITE_PLACEHOLDER: 'name@example.com',
  SETTINGS_ORGANIZATIONS_INVITE_ACTION: 'Invite',
  SETTINGS_ORGANIZATIONS_RESEND: 'Resend',
  SETTINGS_ORGANIZATIONS_CANCEL_INVITE: 'Cancel',
  SETTINGS_ORGANIZATIONS_KICK: 'Kick',
  SETTINGS_ORGANIZATIONS_NO_ADMIN: 'You are not an admin in any organization.',
  SETTINGS_WORK_AVAILABLE_PER_DAY: 'Available per day',
  SETTINGS_WORK_WORK_DAYS: 'Work days',
  SETTINGS_WORK_ORGANIZATIONS: 'Organizations',
  SETTINGS_WORK_LEGEND: 'Legend',
  SETTINGS_WORK_WITHIN_LIMIT: 'Within limit',
  SETTINGS_WORK_NEAR_LIMIT: 'Near limit',
  SETTINGS_WORK_OVERBOOKED: 'Overbooked',
  SETTINGS_WORK_TIME: 'Time',
  SETTINGS_WORK_OFF: 'Off',
  LIST_FILTER_ALL: 'All',
  LIST_FILTER_OPEN: 'Open',
  LIST_FILTER_TODAY: 'Today',
  LIST_FILTER_DONE: 'Done',
  LIST_STAT_OVERALL: 'Overall',
  LIST_STAT_OPEN: 'Open',
  LIST_STAT_DONE: 'Done',
  LIST_NO_TASKS: 'No tasks found',
  LIST_DUE_DATE: 'DueDate:',
  LIST_PROGRESS: 'Progress',
  LIST_COLLAPSE: 'Collapse',
  LIST_EXPAND: 'Expand',
  LIST_MARK_DONE: 'Mark as done',
  LIST_MARK_OPEN: 'Mark as open',
  LIST_DELETE: 'Delete',
  LIST_DONE_BADGE: 'Done',
  TASK_MODAL_EDIT_TITLE: 'Edit Task',
  TASK_MODAL_NEW_TITLE: 'New Task',
  TASK_MODAL_CLOSE: 'Close dialog',
  TASK_MODAL_CREATE_ARIA: 'Create task',
  TASK_MODAL_MODE_STATIC: 'Static',
  TASK_MODAL_MODE_PLANNED: 'Planned',
  TASK_MODAL_TITLE_LABEL: 'Title',
  TASK_MODAL_TITLE_PLACEHOLDER: 'Task title',
  TASK_MODAL_DESCRIPTION_LABEL: 'Description',
  TASK_MODAL_DESCRIPTION_PLACEHOLDER: 'Add a description...',
  TASK_MODAL_ACCOUNT_LABEL: 'Account',
  TASK_MODAL_BLOCKER_LABEL: 'Blocker',
  TASK_MODAL_DIFFICULTY_LABEL: 'Difficulty',
  TASK_MODAL_LABELS_LABEL: 'Labels',
  TASK_MODAL_LABELS_PLACEHOLDER: 'Type a label and press Enter',
  TASK_MODAL_START_DATE_LABEL: 'Start Date',
  TASK_MODAL_END_DATE_LABEL: 'End Date',
  TASK_MODAL_DUE_DATE_LABEL: 'Due Date',
  TASK_MODAL_TIME_LABEL: 'Time',
  TASK_MODAL_FREQUENCY_LABEL: 'Frequency',
  TASK_MODAL_DURATION_LABEL: 'Duration (minutes)',
  TASK_MODAL_DEPENDENCIES_LABEL: 'Dependencies',
  TASK_MODAL_SELECT_TASK: 'Select a task',
  TASK_MODAL_MIN_SCOPE_LABEL: 'Min Scope Duration (min)',
  TASK_MODAL_MAX_SCOPE_LABEL: 'Max Scope Duration (min)',
  TASK_MODAL_DELETE: 'Delete',
  TASK_MODAL_SAVING: 'Saving...',
  TASK_MODAL_UPDATE: 'Update Task',
  TASK_MODAL_CREATE: 'Create Task',
  LINK_ACCOUNT_SUCCESS: 'Successfully linked!',
  LINK_ACCOUNT_ERROR: 'An error occurred while connecting',
  NOTIFICATION_DISMISS: 'Dismiss notification',
  COMMON_CANCEL: 'Cancel',
  COMMON_SAVE: 'Save',
  COMMON_DELETE: 'Delete',
  COMMON_CLOSE: 'Close',
  WEEKDAY_MON: 'Mon',
  WEEKDAY_TUE: 'Tue',
  WEEKDAY_WED: 'Wed',
  WEEKDAY_THU: 'Thu',
  WEEKDAY_FRI: 'Fri',
  WEEKDAY_SAT: 'Sat',
  WEEKDAY_SUN: 'Sun',
  UPCOMING_NO_TASKS: 'No upcoming tasks',
  UPCOMING_OVERDUE_TITLE: 'Running late?',
  UPCOMING_OVERDUE_DESC: 'How many more minutes do you need to finish "{{task}}"?',
  UPCOMING_OVERDUE_LABEL: 'Additional minutes needed',
  UPCOMING_OVERDUE_SUBMIT: 'Update plan',
  UPCOMING_MARK_DONE: 'Mark scope as done',
  UPCOMING_UPDATE_TIME: 'Update remaining time',
  TOAST_TASK_CREATED: 'Task created',
  TOAST_TASK_UPDATED: 'Task updated',
  TOAST_TASK_DELETED: 'Task deleted',
  TOAST_WORK_SCHEDULE_SAVED: 'Work schedule saved',
  TOAST_PLANNING_SUCCEEDED: 'Planning succeeded',
  TOAST_CONNECTION_ERROR_TITLE: 'Connection Error',
  TOAST_CONNECTION_ERROR_MESSAGE: 'Unable to reach the server. Please check your connection.',
  ERROR_TITLE_API_NOT_IMPLEMENTED: 'Not Implemented',
  ERROR_TITLE_INSUFFICIENT_SLOTS: 'Planning Failed',
  ERROR_TITLE_RESOURCE_NOT_FOUND: 'Not Found',
  ERROR_TITLE_VALIDATION_ERROR: 'Validation Failed',
  ERROR_TITLE_INVALID_REQUEST: 'Invalid Request',
  ERROR_TITLE_ACCESS_DENIED: 'Access Denied',
  ERROR_TITLE_ACCOUNT_NOT_FOUND: 'Account Not Found',
  ERROR_TITLE_INTERNAL_SERVER_ERROR: 'Internal Server Error',
  ERROR_FALLBACK_SERVER: 'Server Error',
  ERROR_FALLBACK_NOT_FOUND: 'Not Found',
  ERROR_FALLBACK_FORBIDDEN: 'Access Denied',
  ERROR_FALLBACK_UNAUTHORIZED: 'Unauthorized',
  ERROR_FALLBACK_REQUEST: 'Request Error',
  ERROR_FALLBACK_GENERIC: 'Error',
  ERROR_FALLBACK_MESSAGE: 'An unexpected error occurred',
};

/**
 * Provides Transloco providers for unit tests with real EN translations.
 * Import this module in TestBed.configureTestingModule({ imports: [...] })
 */
export function getTranslocoTestingModule() {
  return TranslocoTestingModule.forRoot({
    translocoConfig: {
      availableLangs: ['en', 'de'],
      defaultLang: 'en',
    },
    preloadLangs: true,
    langs: {
      en,
    },
  });
}
