/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountLinkConfirmRequest } from '../../models/account-link-confirm-request';
import { AccountLinkConfirmResponse } from '../../models/account-link-confirm-response';

export interface ConfirmAccountLink$Params {
      body: AccountLinkConfirmRequest
}

export function confirmAccountLink(http: HttpClient, rootUrl: string, params: ConfirmAccountLink$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountLinkConfirmResponse>> {
  const rb = new RequestBuilder(rootUrl, confirmAccountLink.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountLinkConfirmResponse>;
    })
  );
}

confirmAccountLink.PATH = '/v1/identity/accounts/confirm';
