/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdentityResponse } from '../../models/identity-response';

export interface GetIdentity$Params {
}

export function getIdentity(http: HttpClient, rootUrl: string, params?: GetIdentity$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentityResponse>> {
  const rb = new RequestBuilder(rootUrl, getIdentity.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdentityResponse>;
    })
  );
}

getIdentity.PATH = '/v1/identity';
