/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdentityOrganizationColorResponse } from '../../models/identity-organization-color-response';
import { IdentityOrganizationColorUpdateRequest } from '../../models/identity-organization-color-update-request';

export interface UpdateOrganizationColor$Params {
  organizationId: string;
      body: IdentityOrganizationColorUpdateRequest
}

export function updateOrganizationColor(http: HttpClient, rootUrl: string, params: UpdateOrganizationColor$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentityOrganizationColorResponse>> {
  const rb = new RequestBuilder(rootUrl, updateOrganizationColor.PATH, 'put');
  if (params) {
    rb.path('organizationId', params.organizationId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdentityOrganizationColorResponse>;
    })
  );
}

updateOrganizationColor.PATH = '/v1/identity/colors/{organizationId}';
