/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkSlotCreateRequest } from '../../models/work-slot-create-request';
import { WorkSlotResponse } from '../../models/work-slot-response';

export interface CreateWorkSlot$Params {
      body: WorkSlotCreateRequest
}

export function createWorkSlot(http: HttpClient, rootUrl: string, params: CreateWorkSlot$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkSlotResponse>> {
  const rb = new RequestBuilder(rootUrl, createWorkSlot.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkSlotResponse>;
    })
  );
}

createWorkSlot.PATH = '/v1/workslots';
