/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkSlotResponse } from '../../models/work-slot-response';

export interface GetWorkSlots$Params {
}

export function getWorkSlots(http: HttpClient, rootUrl: string, params?: GetWorkSlots$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkSlotResponse>>> {
  const rb = new RequestBuilder(rootUrl, getWorkSlots.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkSlotResponse>>;
    })
  );
}

getWorkSlots.PATH = '/v1/workslots';
