/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScopeResponse } from '../../models/scope-response';

export interface GetScopes$Params {
}

export function getScopes(http: HttpClient, rootUrl: string, params?: GetScopes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ScopeResponse>>> {
  const rb = new RequestBuilder(rootUrl, getScopes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ScopeResponse>>;
    })
  );
}

getScopes.PATH = '/v1/scopes';
