/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LabelResponse } from '../../models/label-response';

export interface TestEndpoint3$Params {
}

export function testEndpoint3(http: HttpClient, rootUrl: string, params?: TestEndpoint3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LabelResponse>>> {
  const rb = new RequestBuilder(rootUrl, testEndpoint3.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LabelResponse>>;
    })
  );
}

testEndpoint3.PATH = '/test/labels';
