/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganizationResponse } from '../models/organization-response';
export interface AccountResponse {
  id?: number;
  identityId?: number;
  organizations?: Array<OrganizationResponse>;
}
