/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskUpdateRequest } from '../models/task-update-request';

/**
 * Update request for a dynamic (schedulable) task
 */
export type DynamicTaskUpdateRequest = TaskUpdateRequest & {
  dependencies?: Array<number>;
  description?: string;
  difficulty?: number;
  duration?: string;
  elapsed?: string;
  endAt?: string;
  labels?: Array<LabelCreateRequest>;
  maxScopeDuration?: string;
  minScopeDuration?: string;
  name?: string;
  organizationId?: number;
  rrule?: string;
  startAt?: string;
};
