/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskCreateRequest } from '../models/task-create-request';

/**
 * Create request for a dynamic (schedulable) task with duration and scope constraints
 */
export type DynamicTaskCreateRequest = TaskCreateRequest & {
  accountId?: number;
  description?: string;
  difficulty?: number;
  duration?: number;
  endAt?: string;
  labels?: Array<LabelCreateRequest>;
  maxScopeDuration?: number;
  minScopeDuration?: number;
  name?: string;
  rrule?: string;
  startAt?: string;
};
