/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskCreateRequest } from '../models/task-create-request';

/**
 * Create request for a dynamic (schedulable) task with duration and scope constraints
 */
export type DynamicTaskCreateRequest = TaskCreateRequest & {
'dependencies'?: Array<number>;
'description'?: string;
'difficulty'?: 'TRIVIAL' | 'EASY' | 'MEDIUM' | 'HARD' | 'EXTREME';
'duration'?: string;
'endAt'?: string;
'labels'?: Array<LabelCreateRequest>;
'maxScopeDuration'?: string;
'minScopeDuration'?: string;
'name'?: string;
'organizationId'?: string;
'startAt'?: string;
};

