/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelResponse } from '../models/label-response';
import { ScopeResponse } from '../models/scope-response';
import { TaskResponse } from '../models/task-response';

/**
 * Response for a dynamic (schedulable) task, including its scopes and dependencies
 */
export type DynamicTaskResponse = TaskResponse & {
'dependencies'?: Array<number>;
'dependents'?: Array<number>;
'description'?: string;
'difficulty'?: 'TRIVIAL' | 'EASY' | 'MEDIUM' | 'HARD' | 'EXTREME';
'duration'?: string;
'elapsed'?: string;
'endAt'?: string;
'id'?: number;
'labels'?: Array<LabelResponse>;
'maxScopeDuration'?: string;
'minScopeDuration'?: string;
'name'?: string;
'organizationId'?: string;
'scopes'?: Array<ScopeResponse>;
'startAt'?: string;
};

