/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskUpdateRequest } from '../models/task-update-request';

/**
 * Update request for a dynamic (schedulable) task
 */
export type DynamicTaskUpdateRequest = TaskUpdateRequest & {
  description?: string;
  difficulty?: number;
  duration?: number;
  elapsed?: number;
  endAt?: string;
  labels?: Array<LabelCreateRequest>;
  maxScopeDuration?: number;
  minScopeDuration?: number;
  name?: string;
  rrule?: string;
  startAt?: string;
};
