/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelResponse } from '../models/label-response';
import { ScopeResponse } from '../models/scope-response';
import { TaskDependencyResponse } from '../models/task-dependency-response';
import { TaskResponse } from '../models/task-response';

/**
 * Response for a dynamic (schedulable) task, including its scopes and dependencies
 */
export type DynamicTaskResponse = TaskResponse & {
  accountId?: number;
  dependencies?: Array<TaskDependencyResponse>;
  description?: string;
  difficulty?: number;
  duration?: number;
  elapsed?: number;
  endAt?: string;
  id?: number;
  labels?: Array<LabelResponse>;
  maxScopeDuration?: number;
  minScopeDuration?: number;
  name?: string;
  rrule?: string;
  scopes?: Array<ScopeResponse>;
  startAt?: string;
};
