/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountResponse } from '../models/account-response';
export interface IdentityResponse {
  accounts?: Array<AccountResponse>;
  id?: number;
}
