/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IdentityOrganizationColorUpdateRequest {
  color: 'UNSET' | 'RED' | 'ORANGE' | 'AMBER' | 'YELLOW' | 'GREEN' | 'MINT' | 'CYAN' | 'BLUE' | 'INDIGO' | 'PURPLE' | 'PINK' | 'BROWN' | 'GRAY';
}
