/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountResponse } from '../models/account-response';
import { Organization } from '../models/organization';
export interface IdentityResponse {
  accounts: Array<AccountResponse>;

  /**
   * Organization names for which the authenticated identity has admin privileges, derived from JWT groups below /org-admin.
   */
  adminOrganizations: Array<string>;
  id: number;

  /**
   * Organizations to which the identity belongs.
   */
  organizations: Array<Organization>;
}
