/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Invitation {
  email: string;
  expired: boolean;
  expiresAt: string;
  firstName: string;
  id: string;
  inviteLink: string;
  lastName: string;
}
