/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrganizationMember {
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  userName: string;
}
