/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Invitation } from '../models/invitation';
export interface OrganizationInvitationsResponse {
  invitations: Array<Invitation>;
}
