/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganizationMember } from '../models/organization-member';
export interface OrganizationMembersResponse {
  members: Array<OrganizationMember>;
}
