/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkSettings } from '../models/work-settings';
export interface SettingsUpdateRequest {
  language?: string;
  theme?: string;
  workSettings?: WorkSettings;
}
