/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskCreateRequest } from '../models/task-create-request';

/**
 * Create request for a static (fixed-time) task
 */
export type StaticTaskCreateRequest = TaskCreateRequest & {
'color'?: 'UNSET' | 'RED' | 'ORANGE' | 'AMBER' | 'YELLOW' | 'GREEN' | 'MINT' | 'CYAN' | 'BLUE' | 'INDIGO' | 'PURPLE' | 'PINK' | 'BROWN' | 'GRAY';
'description'?: string;
'difficulty'?: 'TRIVIAL' | 'EASY' | 'MEDIUM' | 'HARD' | 'EXTREME';
'endAt'?: string;
'isBlocker'?: boolean;
'labels'?: Array<LabelCreateRequest>;
'name'?: string;

/**
 * Organization ID. Required unless this static task is a blocker.
 */
'organizationId'?: string;
'rrule'?: string;
'startAt'?: string;
};

