/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskUpdateRequest } from '../models/task-update-request';

/**
 * Update request for a static (fixed-time) task
 */
export type StaticTaskUpdateRequest = TaskUpdateRequest & {
'color'?: 'UNSET' | 'RED' | 'ORANGE' | 'AMBER' | 'YELLOW' | 'GREEN' | 'MINT' | 'CYAN' | 'BLUE' | 'INDIGO' | 'PURPLE' | 'PINK' | 'BROWN' | 'GRAY';
'description'?: string;
'difficulty'?: 'TRIVIAL' | 'EASY' | 'MEDIUM' | 'HARD' | 'EXTREME';
'endAt'?: string;
'isBlocker'?: boolean;
'labels'?: Array<LabelCreateRequest>;
'name'?: string;
'organizationId'?: string;
'rrule'?: string;
'startAt'?: string;
};

