/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelResponse } from '../models/label-response';
import { TaskResponse } from '../models/task-response';

/**
 * Response for a static (fixed-time) task
 */
export type StaticTaskResponse = TaskResponse & {
  accountId?: number;
  description?: string;
  difficulty?: number;
  endAt?: string;
  id?: number;
  isBlocker?: boolean;
  labels?: Array<LabelResponse>;
  name?: string;
  rrule?: string;
  startAt?: string;
};
