/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskCreateRequest } from '../models/task-create-request';

/**
 * Create request for a static (fixed-time) task
 */
export type StaticTaskCreateRequest = TaskCreateRequest & {
  accountId?: number;
  description?: string;
  difficulty?: number;
  endAt?: string;
  isBlocker?: boolean;
  labels?: Array<LabelCreateRequest>;
  name?: string;
  rrule?: string;
  startAt?: string;
};
