/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelCreateRequest } from '../models/label-create-request';
import { TaskUpdateRequest } from '../models/task-update-request';

/**
 * Update request for a static (fixed-time) task
 */
export type StaticTaskUpdateRequest = TaskUpdateRequest & {
  description?: string;
  difficulty?: number;
  endAt?: string;
  isBlocker?: boolean;
  labels?: Array<LabelCreateRequest>;
  name?: string;
  rrule?: string;
  startAt?: string;
};
