/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabelResponse } from '../models/label-response';
import { TaskResponse } from '../models/task-response';

/**
 * Response for a static (fixed-time) task
 */
export type StaticTaskResponse = TaskResponse & {
'description'?: string;
'difficulty'?: 'TRIVIAL' | 'EASY' | 'MEDIUM' | 'HARD' | 'EXTREME';
'endAt'?: string;
'id'?: number;
'isBlocker'?: boolean;
'labels'?: Array<LabelResponse>;
'name'?: string;

/**
 * Organization ID. Null for blocker tasks that are not assigned to an organizationId.
 */
'organizationId'?: (string | null);
'rrule'?: string;
'startAt'?: string;
};

