/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkSlotCreateRequest {
  accountId: number;
  endAt: string;
  organizationId: number;
  startAt: string;
}
