/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkSlotResponse {
  accountId?: number;
  endAt?: string;
  id?: number;
  organizationId?: number;
  startAt?: string;
}
